#!/bin/bash

usage() { 
	echo "Show yes/no dialog, returns 0 or 1 depending on user answer"
	echo "Usage: $0 [OPTIONS]
	-x		force to use GUI dialog
	-m <string>	message that user will see" 1>&2
	exit 1;
}

while getopts m:xh opts; do
	case ${opts} in
		x) FORCE_GUI=true;
			;;
		m) MSG=${OPTARG}
			;;
		h) usage
			;;
	esac
done

if [ -z "$MSG" ];then
	usage
fi

# Yes/no dialog. The first argument is the message that the user will see.
# If the user enters n/N, send return 1.
while true; do
	if [ -z $FORCE_GUI ]; then
		read -p "$MSG" yn
		case "$yn" in
			[Yy] )
				exit 0;;
			[Nn] )
				echo "Aborting..." >&1
				exit 1;;
			* )
				echo "Please answer y or n for yes or no.";;
		esac
	else
		if [ -z $DISPLAY ]; then echo "DISPLAY variable is not set" >&1 ; exit 1; fi
		if zenity --question --text="$MSG" --ok-label=Yes --cancel-label=No; then
			exit 0
		else
			echo "Aborting..." >&1
			exit 1
		fi
	fi
done;
